spring.application.name=be

spring.datasource.url=jdbc:postgresql://dpg-dah5m8ijnfac738dmuu0-a.virginia-postgres.render.com:5432/cleaner_bxtc
spring.datasource.username=${DB_USERNAME:myuser}
spring.datasource.password=${DB_PASSWORD:Lw5U6KmoQwymUDkK5PII4bfwQYQ74W2o}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
